# Generated by Django 5.2.7 on 2025-10-12 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reservation_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 12, 16, 32, 21, 515271)),
        ),
    ]
