# Generated by Django 5.2.7 on 2025-10-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_order_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reservation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
