# Generated by Django 5.2.7 on 2025-10-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='allergen',
            field=models.CharField(choices=[('PE', 'Peanuts'), ('WH', 'Wheat'), ('DA', 'Dairy'), ('SF', 'Shellfish'), ('NA', 'None')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
