# Generated by Django 5.2.7 on 2025-10-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=250, null=True, verbose_name='Item descritption')),
                ('ingredients', models.TextField(max_length=250, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('unti_price', models.FloatField()),
                ('portions', models.IntegerField(default=1)),
            ],
        ),
    ]
