# Generated by Django 5.2.7 on 2025-10-11 23:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=250, null=True, verbose_name='Item descritption')),
                ('ingredients', models.TextField(max_length=250, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('unit_price', models.FloatField()),
                ('portions', models.IntegerField(default=1)),
                ('alergens', models.CharField(choices=[('PE', 'Peanuts'), ('WH', 'Wheat'), ('SF', 'Shellfish'), ('NA', 'None')], default='NA')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('O', 'Open'), ('P', 'Placed'), ('R', 'Ready'), ('C', 'Closed')], default='O', max_length=1)),
                ('order_type', models.CharField(choices=[('P', 'Pickup'), ('D', 'Delivery'), ('I', 'Dine In')], default='I', max_length=1)),
                ('party', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('reservation_time', models.DateTimeField()),
                ('table_no', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=25)),
                ('region', models.CharField(max_length=25, verbose_name='Region/Neighberhood')),
                ('city', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.useraddress'),
        ),
    ]
