# Generated by Django 5.2.7 on 2025-10-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='email',
            field=models.CharField(blank=True, default=1, max_length=25),
            preserve_default=False,
        ),
    ]
