# Generated by Django 5.2.7 on 2025-10-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order_rename_unti_price_menu_unit_price_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmation_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('P', 'Placed'), ('R', 'Ready'), ('C', 'Closed')], default='O', max_length=1),
        ),
    ]
