# Generated by Django 5.2.7 on 2025-10-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_order_reservation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_placed',
        ),
    ]
