# Generated by Django 5.2.7 on 2025-10-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_order_date_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='alergens',
            field=models.CharField(choices=[('PE', 'Peanuts'), ('WH', 'Wheat'), ('SF', 'Shellfish'), ('NA', 'None')], default='NA'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('P', 'Pickup'), ('D', 'Delivery'), ('I', 'Dine In')], default='I', max_length=1),
        ),
    ]
