# Generated by Django 5.2.7 on 2025-10-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_menu_alergens_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
